retrive_news_task:
  description: >
    Conduct a thorough research about {topic}
    Make sure you find any interesting and relevant information given
    the current year is {current_year}.
  expected_output: >
    A list with 15 websites with the most relevant information about {topic}
  agent: retrive_news

Website_scrapper_task:
  description: >
    scrap the website for the latest news and information about {topic}
  expected_output: >
    Fully scraped website with all the important information from the website
  agent: Website_scrapper

ai_news_writer_task:
  description: >
    Write a news article to a File_saver
    Make sure the article is well written and informative
  expected_output: >
    A Fully fleged news article with the main topics  , each with a full section of information,
    formated as markdown without '```'
  agent: ai_news_writer

File_saver_task:
  description: >
    Save the news article to a file
  expected_output: >
    A Fully fleged news article with all the information from previous task into a filed name news/{date}_news-article.md 
  agent: File_saver
  